name: Waka Readme

on:
  schedule:
    # Runs at 12 AM Australian Time IST
    - cron: "30 15 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # By Default, It will show all the 'Flags', Write Codes blow when you want to remove some 'Flags'
          LOCALE: "en"
          SHOW_SHORT_INFO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          # Programming Lanugage Related
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TIMEZONE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_PROJECTS: "True"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          # Chart Related
          SHOW_LOC_CHART: "False"
          SHOW_DEBUG_LOGGING: "False"
